---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Actualització dels paquets
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Instal·lar Apache
      apt: name=apache2 update_cache=yes state=latest

    - name: Instal·lar ufw
      apt: name=ufw update_cache=yes state=latest

    - name: Creació del document arrel
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Copiar el codi de la pàgina
      template:
        src: "files/index.html.j2"
        dest: "/var/www/{{ http_host }}/index.html"

    - name: Configurar el Virtualhost d'Apache
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"

    - name: Activació de la pàgina web
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: Desactivació de la pàgina per defecte
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    - name: "UFW - Obrir el port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
