---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Actualització dels paquets
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Instal·lar Git
      apt: name=git update_cache=yes state=latest

    - name: Instal·lar net-tools
      apt: name=net-tools update_cache=yes state=latest
